title: Javier Napoles
description: Portafolio de Diseño Gráfico
url: https://jnapfx.github.io
baseurl: /creative-portfolio
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-seo-tag
collections:
  proyectos:
    output: true
    permalink: /proyectos/:slug/
defaults:
  - scope:
      path: ""
      type: proyectos
    values:
      layout: project
      image: