title: Javier Napoles
description: Portafolio de Diseño Gráfico y Edición de Video.
url: https://jnapfx.github.io
baseurl: /creative-portfolio
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
author:
  name: Javier Napoles
  avatar: 
  bio: Diseñador gráfico y editor de video con 8+ años de experiencia.
  email: jnapfx@gmail.com
  links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/Jnapfx
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/javier-napoles-3513031a7/
logo: 
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-include-cache
- jekyll-remote-theme
markdown: kramdown
highlighter: rouge
permalink: pretty
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: single
    toc: true
    toc_sticky: true
    author_profile: true
footer_scripts:
- /assets/js/dae-link.js
- /assets/js/mobile-menu.js
